---
# tasks file for cni
- name: Install Weave CNI Pluggin
  command: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
  when: weave


# other tasks for other CNI Plugins can be called in the main playbook by listing <name>: true in the vars
#- name: Install Calico CNI Pluggin
#  command: dummy command for calico
#  when: calico