---
- hosts: all
  become: yes
  become_user: root
  vars:
    containerd_config_default_write: true
    containerd_config_cgroup_driver_systemd: true
    #still need to make these defaults in the containerd task
  roles:
    - kernel_config
    - repositories
    - kubeadm
    - kubelet
    - kubectl
    - containerd
  tags: pre-k8s-init

- hosts: controlplane_nodes
  become: yes
  become_user: cloud_user
  vars:
    pod_network_cidr: 10.244.0.0/16
    # pod CIDR range for cluster init, change this to match your CNI pluggin CIDR configuration
    host_ip: "{{ ansible_facts['ansible_all_ipv4_address'] }}"
    host_name: "{{ ansible_facts['node_name'] }}"
  roles:
    - cluster_init
    - cni
  tags: cluster-init

- hosts: worker_nodes
  become: yes
  become_user: cloud_user
  roles:
    - add-node
  tags: add-node