---
- hosts: all
  become: yes
  become_user: root
  vars:
    containerd_config_default_write: true
    containerd_config_cgroup_driver_systemd: true
    kubeadm_version: 1.25.0-00
    kubectl_version: 1.25.0-00
    kubelet_version: 1.25.0-00
  roles:
    - kernel_config
    - repositories
    - kubeadm
    - kubelet
    - kubectl
    - containerd
  tags: pre-k8s-init

- hosts: controlplane_nodes
  become: yes
  become_user: root
  vars:
    pod_network_cidr: 10.244.0.0/16
    # pod CIDR range for cluster init, change this to match your CNI pluggin CIDR configuration
    host_ip: 172.31.23.158 #not sure how to grab this systematically yet
    host_name: k8s-controlplane #this one as well, check old versions for how it used to be set
  roles:
    - cluster_init
    - cni
  tags: cluster-init

- hosts: worker_nodes
  become: yes
  become_user: root
  roles:
    - add-node
  tags: add-node